#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="trader")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbObj(tbObj instance);
    partial void UpdatetbObj(tbObj instance);
    partial void DeletetbObj(tbObj instance);
    partial void InserttsInstruction(tsInstruction instance);
    partial void UpdatetsInstruction(tsInstruction instance);
    partial void DeletetsInstruction(tsInstruction instance);
    partial void InserttsSimplifiedStrategiesObject(tsSimplifiedStrategiesObject instance);
    partial void UpdatetsSimplifiedStrategiesObject(tsSimplifiedStrategiesObject instance);
    partial void DeletetsSimplifiedStrategiesObject(tsSimplifiedStrategiesObject instance);
    partial void InserttbDateLineExt(tbDateLineExt instance);
    partial void UpdatetbDateLineExt(tbDateLineExt instance);
    partial void DeletetbDateLineExt(tbDateLineExt instance);
    partial void InserttbDnWindow(tbDnWindow instance);
    partial void UpdatetbDnWindow(tbDnWindow instance);
    partial void DeletetbDnWindow(tbDnWindow instance);
    #endregion
		
		public DBDataContext() : 
				base(global::ts.Properties.Settings.Default.traderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbObj> tbObjs
		{
			get
			{
				return this.GetTable<tbObj>();
			}
		}
		
		public System.Data.Linq.Table<tsInstruction> tsInstructions
		{
			get
			{
				return this.GetTable<tsInstruction>();
			}
		}
		
		public System.Data.Linq.Table<tsSimplifiedStrategiesObject> tsSimplifiedStrategiesObjects
		{
			get
			{
				return this.GetTable<tsSimplifiedStrategiesObject>();
			}
		}
		
		public System.Data.Linq.Table<tbDateLineExt> tbDateLineExts
		{
			get
			{
				return this.GetTable<tbDateLineExt>();
			}
		}
		
		public System.Data.Linq.Table<tbDnWindow> tbDnWindows
		{
			get
			{
				return this.GetTable<tbDnWindow>();
			}
		}
		
		public System.Data.Linq.Table<tbPairBingoH> tbPairBingoHs
		{
			get
			{
				return this.GetTable<tbPairBingoH>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddSSOAndInstruction")]
		public int spAddSSOAndInstruction([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string sqlSSO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string sqlInstruction, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> idSSO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> idInstruction)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sqlSSO, sqlInstruction, idSSO, idInstruction);
			idSSO = ((System.Nullable<long>)(result.GetParameterValue(2)));
			idInstruction = ((System.Nullable<long>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbObj")]
	public partial class tbObj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public tbObj()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsInstruction")]
	public partial class tsInstruction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _idForObj;
		
		private System.Nullable<decimal> _priceAsc;
		
		private System.Nullable<decimal> _priceDesc;
		
		private short _priceType;
		
		private System.Nullable<decimal> _price;
		
		private short _category;
		
		private int _quantity;
		
		private short _state;
		
		private System.DateTime _generateTime;
		
		private System.Nullable<System.DateTime> _sendTime;
		
		private System.Nullable<System.DateTime> _resultTime;
		
		private string _desc;
		
		private string _desc2;
		
		private EntityRef<tsSimplifiedStrategiesObject> _tsSimplifiedStrategiesObject;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnidForObjChanging(long value);
    partial void OnidForObjChanged();
    partial void OnpriceAscChanging(System.Nullable<decimal> value);
    partial void OnpriceAscChanged();
    partial void OnpriceDescChanging(System.Nullable<decimal> value);
    partial void OnpriceDescChanged();
    partial void OnpriceTypeChanging(short value);
    partial void OnpriceTypeChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OncategoryChanging(short value);
    partial void OncategoryChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    partial void OnstateChanging(short value);
    partial void OnstateChanged();
    partial void OngenerateTimeChanging(System.DateTime value);
    partial void OngenerateTimeChanged();
    partial void OnsendTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnsendTimeChanged();
    partial void OnresultTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnresultTimeChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void Ondesc2Changing(string value);
    partial void Ondesc2Changed();
    #endregion
		
		public tsInstruction()
		{
			this._tsSimplifiedStrategiesObject = default(EntityRef<tsSimplifiedStrategiesObject>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idForObj", DbType="BigInt NOT NULL")]
		public long idForObj
		{
			get
			{
				return this._idForObj;
			}
			set
			{
				if ((this._idForObj != value))
				{
					if (this._tsSimplifiedStrategiesObject.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidForObjChanging(value);
					this.SendPropertyChanging();
					this._idForObj = value;
					this.SendPropertyChanged("idForObj");
					this.OnidForObjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceAsc", DbType="Money")]
		public System.Nullable<decimal> priceAsc
		{
			get
			{
				return this._priceAsc;
			}
			set
			{
				if ((this._priceAsc != value))
				{
					this.OnpriceAscChanging(value);
					this.SendPropertyChanging();
					this._priceAsc = value;
					this.SendPropertyChanged("priceAsc");
					this.OnpriceAscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceDesc", DbType="Money")]
		public System.Nullable<decimal> priceDesc
		{
			get
			{
				return this._priceDesc;
			}
			set
			{
				if ((this._priceDesc != value))
				{
					this.OnpriceDescChanging(value);
					this.SendPropertyChanging();
					this._priceDesc = value;
					this.SendPropertyChanged("priceDesc");
					this.OnpriceDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceType", DbType="SmallInt NOT NULL")]
		public short priceType
		{
			get
			{
				return this._priceType;
			}
			set
			{
				if ((this._priceType != value))
				{
					this.OnpriceTypeChanging(value);
					this.SendPropertyChanging();
					this._priceType = value;
					this.SendPropertyChanged("priceType");
					this.OnpriceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Money")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="SmallInt NOT NULL")]
		public short category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="SmallInt NOT NULL")]
		public short state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_generateTime", DbType="DateTime NOT NULL")]
		public System.DateTime generateTime
		{
			get
			{
				return this._generateTime;
			}
			set
			{
				if ((this._generateTime != value))
				{
					this.OngenerateTimeChanging(value);
					this.SendPropertyChanging();
					this._generateTime = value;
					this.SendPropertyChanged("generateTime");
					this.OngenerateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> sendTime
		{
			get
			{
				return this._sendTime;
			}
			set
			{
				if ((this._sendTime != value))
				{
					this.OnsendTimeChanging(value);
					this.SendPropertyChanging();
					this._sendTime = value;
					this.SendPropertyChanged("sendTime");
					this.OnsendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> resultTime
		{
			get
			{
				return this._resultTime;
			}
			set
			{
				if ((this._resultTime != value))
				{
					this.OnresultTimeChanging(value);
					this.SendPropertyChanging();
					this._resultTime = value;
					this.SendPropertyChanged("resultTime");
					this.OnresultTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(255)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc2", DbType="VarChar(255)")]
		public string desc2
		{
			get
			{
				return this._desc2;
			}
			set
			{
				if ((this._desc2 != value))
				{
					this.Ondesc2Changing(value);
					this.SendPropertyChanging();
					this._desc2 = value;
					this.SendPropertyChanged("desc2");
					this.Ondesc2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsSimplifiedStrategiesObject_tsInstruction", Storage="_tsSimplifiedStrategiesObject", ThisKey="idForObj", OtherKey="id", IsForeignKey=true)]
		public tsSimplifiedStrategiesObject tsSimplifiedStrategiesObject
		{
			get
			{
				return this._tsSimplifiedStrategiesObject.Entity;
			}
			set
			{
				tsSimplifiedStrategiesObject previousValue = this._tsSimplifiedStrategiesObject.Entity;
				if (((previousValue != value) 
							|| (this._tsSimplifiedStrategiesObject.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsSimplifiedStrategiesObject.Entity = null;
						previousValue.tsInstructions.Remove(this);
					}
					this._tsSimplifiedStrategiesObject.Entity = value;
					if ((value != null))
					{
						value.tsInstructions.Add(this);
						this._idForObj = value.id;
					}
					else
					{
						this._idForObj = default(long);
					}
					this.SendPropertyChanged("tsSimplifiedStrategiesObject");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsSimplifiedStrategiesObject")]
	public partial class tsSimplifiedStrategiesObject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _idForStrategies;
		
		private System.DateTime _createTime;
		
		private string _code;
		
		private short _direction;
		
		private int _planQuantity;
		
		private decimal _lastStopPrice;
		
		private short _state;
		
		private string _desc;
		
		private EntitySet<tsInstruction> _tsInstructions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnidForStrategiesChanging(long value);
    partial void OnidForStrategiesChanged();
    partial void OncreateTimeChanging(System.DateTime value);
    partial void OncreateTimeChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndirectionChanging(short value);
    partial void OndirectionChanged();
    partial void OnplanQuantityChanging(int value);
    partial void OnplanQuantityChanged();
    partial void OnlastStopPriceChanging(decimal value);
    partial void OnlastStopPriceChanged();
    partial void OnstateChanging(short value);
    partial void OnstateChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    #endregion
		
		public tsSimplifiedStrategiesObject()
		{
			this._tsInstructions = new EntitySet<tsInstruction>(new Action<tsInstruction>(this.attach_tsInstructions), new Action<tsInstruction>(this.detach_tsInstructions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idForStrategies", DbType="BigInt NOT NULL")]
		public long idForStrategies
		{
			get
			{
				return this._idForStrategies;
			}
			set
			{
				if ((this._idForStrategies != value))
				{
					this.OnidForStrategiesChanging(value);
					this.SendPropertyChanging();
					this._idForStrategies = value;
					this.SendPropertyChanged("idForStrategies");
					this.OnidForStrategiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createTime", DbType="DateTime NOT NULL")]
		public System.DateTime createTime
		{
			get
			{
				return this._createTime;
			}
			set
			{
				if ((this._createTime != value))
				{
					this.OncreateTimeChanging(value);
					this.SendPropertyChanging();
					this._createTime = value;
					this.SendPropertyChanged("createTime");
					this.OncreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="SmallInt NOT NULL")]
		public short direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planQuantity", DbType="Int NOT NULL")]
		public int planQuantity
		{
			get
			{
				return this._planQuantity;
			}
			set
			{
				if ((this._planQuantity != value))
				{
					this.OnplanQuantityChanging(value);
					this.SendPropertyChanging();
					this._planQuantity = value;
					this.SendPropertyChanged("planQuantity");
					this.OnplanQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastStopPrice", DbType="Money NOT NULL")]
		public decimal lastStopPrice
		{
			get
			{
				return this._lastStopPrice;
			}
			set
			{
				if ((this._lastStopPrice != value))
				{
					this.OnlastStopPriceChanging(value);
					this.SendPropertyChanging();
					this._lastStopPrice = value;
					this.SendPropertyChanged("lastStopPrice");
					this.OnlastStopPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="SmallInt NOT NULL")]
		public short state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(255)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsSimplifiedStrategiesObject_tsInstruction", Storage="_tsInstructions", ThisKey="id", OtherKey="idForObj")]
		public EntitySet<tsInstruction> tsInstructions
		{
			get
			{
				return this._tsInstructions;
			}
			set
			{
				this._tsInstructions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsInstructions(tsInstruction entity)
		{
			this.SendPropertyChanging();
			entity.tsSimplifiedStrategiesObject = this;
		}
		
		private void detach_tsInstructions(tsInstruction entity)
		{
			this.SendPropertyChanging();
			entity.tsSimplifiedStrategiesObject = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDateLineExt")]
	public partial class tbDateLineExt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code;
		
		private System.DateTime _date;
		
		private decimal _O;
		
		private decimal _H;
		
		private decimal _L;
		
		private decimal _C;
		
		private System.Nullable<decimal> _V;
		
		private System.Nullable<decimal> _vm;
		
		private System.Nullable<decimal> _lastC;
		
		private System.Nullable<decimal> _ma5;
		
		private System.Nullable<decimal> _ma10;
		
		private System.Nullable<decimal> _ma20;
		
		private System.Nullable<decimal> _ma60;
		
		private System.Nullable<decimal> _atr;
		
		private System.Nullable<decimal> _atr10;
		
		private System.Nullable<double> _ema12;
		
		private System.Nullable<double> _ema26;
		
		private System.Nullable<double> _dif;
		
		private System.Nullable<double> _dea;
		
		private System.Nullable<double> _macd;
		
		private System.Nullable<double> _k;
		
		private System.Nullable<double> _d;
		
		private System.Nullable<double> _j;
		
		private System.Nullable<double> _rsi6;
		
		private System.Nullable<double> _rsi12;
		
		private System.Nullable<double> _rsi24;
		
		private System.Nullable<decimal> _ma30;
		
		private System.Nullable<decimal> _ma250;
		
		private System.Nullable<decimal> _EPS_lastYear;
		
		private System.Nullable<decimal> _EPS_lastQ4;
		
		private System.Nullable<decimal> _EPS_thisYear;
		
		private System.Nullable<decimal> _Flow_of_equity;
		
		private System.Nullable<decimal> _Total_share_capital;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OnOChanging(decimal value);
    partial void OnOChanged();
    partial void OnHChanging(decimal value);
    partial void OnHChanged();
    partial void OnLChanging(decimal value);
    partial void OnLChanged();
    partial void OnCChanging(decimal value);
    partial void OnCChanged();
    partial void OnVChanging(System.Nullable<decimal> value);
    partial void OnVChanged();
    partial void OnvmChanging(System.Nullable<decimal> value);
    partial void OnvmChanged();
    partial void OnlastCChanging(System.Nullable<decimal> value);
    partial void OnlastCChanged();
    partial void Onma5Changing(System.Nullable<decimal> value);
    partial void Onma5Changed();
    partial void Onma10Changing(System.Nullable<decimal> value);
    partial void Onma10Changed();
    partial void Onma20Changing(System.Nullable<decimal> value);
    partial void Onma20Changed();
    partial void Onma60Changing(System.Nullable<decimal> value);
    partial void Onma60Changed();
    partial void OnatrChanging(System.Nullable<decimal> value);
    partial void OnatrChanged();
    partial void Onatr10Changing(System.Nullable<decimal> value);
    partial void Onatr10Changed();
    partial void Onema12Changing(System.Nullable<double> value);
    partial void Onema12Changed();
    partial void Onema26Changing(System.Nullable<double> value);
    partial void Onema26Changed();
    partial void OndifChanging(System.Nullable<double> value);
    partial void OndifChanged();
    partial void OndeaChanging(System.Nullable<double> value);
    partial void OndeaChanged();
    partial void OnmacdChanging(System.Nullable<double> value);
    partial void OnmacdChanged();
    partial void OnkChanging(System.Nullable<double> value);
    partial void OnkChanged();
    partial void OndChanging(System.Nullable<double> value);
    partial void OndChanged();
    partial void OnjChanging(System.Nullable<double> value);
    partial void OnjChanged();
    partial void Onrsi6Changing(System.Nullable<double> value);
    partial void Onrsi6Changed();
    partial void Onrsi12Changing(System.Nullable<double> value);
    partial void Onrsi12Changed();
    partial void Onrsi24Changing(System.Nullable<double> value);
    partial void Onrsi24Changed();
    partial void Onma30Changing(System.Nullable<decimal> value);
    partial void Onma30Changed();
    partial void Onma250Changing(System.Nullable<decimal> value);
    partial void Onma250Changed();
    partial void OnEPS_lastYearChanging(System.Nullable<decimal> value);
    partial void OnEPS_lastYearChanged();
    partial void OnEPS_lastQ4Changing(System.Nullable<decimal> value);
    partial void OnEPS_lastQ4Changed();
    partial void OnEPS_thisYearChanging(System.Nullable<decimal> value);
    partial void OnEPS_thisYearChanged();
    partial void OnFlow_of_equityChanging(System.Nullable<decimal> value);
    partial void OnFlow_of_equityChanged();
    partial void OnTotal_share_capitalChanging(System.Nullable<decimal> value);
    partial void OnTotal_share_capitalChanged();
    #endregion
		
		public tbDateLineExt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O", DbType="Money NOT NULL")]
		public decimal O
		{
			get
			{
				return this._O;
			}
			set
			{
				if ((this._O != value))
				{
					this.OnOChanging(value);
					this.SendPropertyChanging();
					this._O = value;
					this.SendPropertyChanged("O");
					this.OnOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Money NOT NULL")]
		public decimal H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this.OnHChanging(value);
					this.SendPropertyChanging();
					this._H = value;
					this.SendPropertyChanged("H");
					this.OnHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L", DbType="Money NOT NULL")]
		public decimal L
		{
			get
			{
				return this._L;
			}
			set
			{
				if ((this._L != value))
				{
					this.OnLChanging(value);
					this.SendPropertyChanging();
					this._L = value;
					this.SendPropertyChanged("L");
					this.OnLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Money NOT NULL")]
		public decimal C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this.OnCChanging(value);
					this.SendPropertyChanging();
					this._C = value;
					this.SendPropertyChanged("C");
					this.OnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> V
		{
			get
			{
				return this._V;
			}
			set
			{
				if ((this._V != value))
				{
					this.OnVChanging(value);
					this.SendPropertyChanging();
					this._V = value;
					this.SendPropertyChanged("V");
					this.OnVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vm", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> vm
		{
			get
			{
				return this._vm;
			}
			set
			{
				if ((this._vm != value))
				{
					this.OnvmChanging(value);
					this.SendPropertyChanging();
					this._vm = value;
					this.SendPropertyChanged("vm");
					this.OnvmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastC", DbType="Money")]
		public System.Nullable<decimal> lastC
		{
			get
			{
				return this._lastC;
			}
			set
			{
				if ((this._lastC != value))
				{
					this.OnlastCChanging(value);
					this.SendPropertyChanging();
					this._lastC = value;
					this.SendPropertyChanged("lastC");
					this.OnlastCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma5", DbType="Money")]
		public System.Nullable<decimal> ma5
		{
			get
			{
				return this._ma5;
			}
			set
			{
				if ((this._ma5 != value))
				{
					this.Onma5Changing(value);
					this.SendPropertyChanging();
					this._ma5 = value;
					this.SendPropertyChanged("ma5");
					this.Onma5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma10", DbType="Money")]
		public System.Nullable<decimal> ma10
		{
			get
			{
				return this._ma10;
			}
			set
			{
				if ((this._ma10 != value))
				{
					this.Onma10Changing(value);
					this.SendPropertyChanging();
					this._ma10 = value;
					this.SendPropertyChanged("ma10");
					this.Onma10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma20", DbType="Money")]
		public System.Nullable<decimal> ma20
		{
			get
			{
				return this._ma20;
			}
			set
			{
				if ((this._ma20 != value))
				{
					this.Onma20Changing(value);
					this.SendPropertyChanging();
					this._ma20 = value;
					this.SendPropertyChanged("ma20");
					this.Onma20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma60", DbType="Money")]
		public System.Nullable<decimal> ma60
		{
			get
			{
				return this._ma60;
			}
			set
			{
				if ((this._ma60 != value))
				{
					this.Onma60Changing(value);
					this.SendPropertyChanging();
					this._ma60 = value;
					this.SendPropertyChanged("ma60");
					this.Onma60Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atr", DbType="Money")]
		public System.Nullable<decimal> atr
		{
			get
			{
				return this._atr;
			}
			set
			{
				if ((this._atr != value))
				{
					this.OnatrChanging(value);
					this.SendPropertyChanging();
					this._atr = value;
					this.SendPropertyChanged("atr");
					this.OnatrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atr10", DbType="Money")]
		public System.Nullable<decimal> atr10
		{
			get
			{
				return this._atr10;
			}
			set
			{
				if ((this._atr10 != value))
				{
					this.Onatr10Changing(value);
					this.SendPropertyChanging();
					this._atr10 = value;
					this.SendPropertyChanged("atr10");
					this.Onatr10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ema12", DbType="Float")]
		public System.Nullable<double> ema12
		{
			get
			{
				return this._ema12;
			}
			set
			{
				if ((this._ema12 != value))
				{
					this.Onema12Changing(value);
					this.SendPropertyChanging();
					this._ema12 = value;
					this.SendPropertyChanged("ema12");
					this.Onema12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ema26", DbType="Float")]
		public System.Nullable<double> ema26
		{
			get
			{
				return this._ema26;
			}
			set
			{
				if ((this._ema26 != value))
				{
					this.Onema26Changing(value);
					this.SendPropertyChanging();
					this._ema26 = value;
					this.SendPropertyChanged("ema26");
					this.Onema26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dif", DbType="Float")]
		public System.Nullable<double> dif
		{
			get
			{
				return this._dif;
			}
			set
			{
				if ((this._dif != value))
				{
					this.OndifChanging(value);
					this.SendPropertyChanging();
					this._dif = value;
					this.SendPropertyChanged("dif");
					this.OndifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dea", DbType="Float")]
		public System.Nullable<double> dea
		{
			get
			{
				return this._dea;
			}
			set
			{
				if ((this._dea != value))
				{
					this.OndeaChanging(value);
					this.SendPropertyChanging();
					this._dea = value;
					this.SendPropertyChanged("dea");
					this.OndeaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macd", DbType="Float")]
		public System.Nullable<double> macd
		{
			get
			{
				return this._macd;
			}
			set
			{
				if ((this._macd != value))
				{
					this.OnmacdChanging(value);
					this.SendPropertyChanging();
					this._macd = value;
					this.SendPropertyChanged("macd");
					this.OnmacdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k", DbType="Float")]
		public System.Nullable<double> k
		{
			get
			{
				return this._k;
			}
			set
			{
				if ((this._k != value))
				{
					this.OnkChanging(value);
					this.SendPropertyChanging();
					this._k = value;
					this.SendPropertyChanged("k");
					this.OnkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Float")]
		public System.Nullable<double> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this.OndChanging(value);
					this.SendPropertyChanging();
					this._d = value;
					this.SendPropertyChanged("d");
					this.OndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j", DbType="Float")]
		public System.Nullable<double> j
		{
			get
			{
				return this._j;
			}
			set
			{
				if ((this._j != value))
				{
					this.OnjChanging(value);
					this.SendPropertyChanging();
					this._j = value;
					this.SendPropertyChanged("j");
					this.OnjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rsi6", DbType="Float")]
		public System.Nullable<double> rsi6
		{
			get
			{
				return this._rsi6;
			}
			set
			{
				if ((this._rsi6 != value))
				{
					this.Onrsi6Changing(value);
					this.SendPropertyChanging();
					this._rsi6 = value;
					this.SendPropertyChanged("rsi6");
					this.Onrsi6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rsi12", DbType="Float")]
		public System.Nullable<double> rsi12
		{
			get
			{
				return this._rsi12;
			}
			set
			{
				if ((this._rsi12 != value))
				{
					this.Onrsi12Changing(value);
					this.SendPropertyChanging();
					this._rsi12 = value;
					this.SendPropertyChanged("rsi12");
					this.Onrsi12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rsi24", DbType="Float")]
		public System.Nullable<double> rsi24
		{
			get
			{
				return this._rsi24;
			}
			set
			{
				if ((this._rsi24 != value))
				{
					this.Onrsi24Changing(value);
					this.SendPropertyChanging();
					this._rsi24 = value;
					this.SendPropertyChanged("rsi24");
					this.Onrsi24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma30", DbType="Money")]
		public System.Nullable<decimal> ma30
		{
			get
			{
				return this._ma30;
			}
			set
			{
				if ((this._ma30 != value))
				{
					this.Onma30Changing(value);
					this.SendPropertyChanging();
					this._ma30 = value;
					this.SendPropertyChanged("ma30");
					this.Onma30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma250", DbType="Money")]
		public System.Nullable<decimal> ma250
		{
			get
			{
				return this._ma250;
			}
			set
			{
				if ((this._ma250 != value))
				{
					this.Onma250Changing(value);
					this.SendPropertyChanging();
					this._ma250 = value;
					this.SendPropertyChanged("ma250");
					this.Onma250Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPS_lastYear", DbType="Money")]
		public System.Nullable<decimal> EPS_lastYear
		{
			get
			{
				return this._EPS_lastYear;
			}
			set
			{
				if ((this._EPS_lastYear != value))
				{
					this.OnEPS_lastYearChanging(value);
					this.SendPropertyChanging();
					this._EPS_lastYear = value;
					this.SendPropertyChanged("EPS_lastYear");
					this.OnEPS_lastYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPS_lastQ4", DbType="Money")]
		public System.Nullable<decimal> EPS_lastQ4
		{
			get
			{
				return this._EPS_lastQ4;
			}
			set
			{
				if ((this._EPS_lastQ4 != value))
				{
					this.OnEPS_lastQ4Changing(value);
					this.SendPropertyChanging();
					this._EPS_lastQ4 = value;
					this.SendPropertyChanged("EPS_lastQ4");
					this.OnEPS_lastQ4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPS_thisYear", DbType="Money")]
		public System.Nullable<decimal> EPS_thisYear
		{
			get
			{
				return this._EPS_thisYear;
			}
			set
			{
				if ((this._EPS_thisYear != value))
				{
					this.OnEPS_thisYearChanging(value);
					this.SendPropertyChanging();
					this._EPS_thisYear = value;
					this.SendPropertyChanged("EPS_thisYear");
					this.OnEPS_thisYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flow_of_equity", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> Flow_of_equity
		{
			get
			{
				return this._Flow_of_equity;
			}
			set
			{
				if ((this._Flow_of_equity != value))
				{
					this.OnFlow_of_equityChanging(value);
					this.SendPropertyChanging();
					this._Flow_of_equity = value;
					this.SendPropertyChanged("Flow_of_equity");
					this.OnFlow_of_equityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_share_capital", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> Total_share_capital
		{
			get
			{
				return this._Total_share_capital;
			}
			set
			{
				if ((this._Total_share_capital != value))
				{
					this.OnTotal_share_capitalChanging(value);
					this.SendPropertyChanging();
					this._Total_share_capital = value;
					this.SendPropertyChanged("Total_share_capital");
					this.OnTotal_share_capitalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDnWindows")]
	public partial class tbDnWindow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code;
		
		private System.DateTime _date;
		
		private short _continuedN;
		
		private decimal _UpWindowMinL;
		
		private decimal _DnWindowMaxH;
		
		private decimal _lastSize;
		
		private decimal _allSize;
		
		private decimal _last2CurrentC;
		
		private decimal _all2CurrentC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OncontinuedNChanging(short value);
    partial void OncontinuedNChanged();
    partial void OnUpWindowMinLChanging(decimal value);
    partial void OnUpWindowMinLChanged();
    partial void OnDnWindowMaxHChanging(decimal value);
    partial void OnDnWindowMaxHChanged();
    partial void OnlastSizeChanging(decimal value);
    partial void OnlastSizeChanged();
    partial void OnallSizeChanging(decimal value);
    partial void OnallSizeChanged();
    partial void Onlast2CurrentCChanging(decimal value);
    partial void Onlast2CurrentCChanged();
    partial void Onall2CurrentCChanging(decimal value);
    partial void Onall2CurrentCChanged();
    #endregion
		
		public tbDnWindow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_continuedN", DbType="SmallInt NOT NULL")]
		public short continuedN
		{
			get
			{
				return this._continuedN;
			}
			set
			{
				if ((this._continuedN != value))
				{
					this.OncontinuedNChanging(value);
					this.SendPropertyChanging();
					this._continuedN = value;
					this.SendPropertyChanged("continuedN");
					this.OncontinuedNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpWindowMinL", DbType="Money NOT NULL")]
		public decimal UpWindowMinL
		{
			get
			{
				return this._UpWindowMinL;
			}
			set
			{
				if ((this._UpWindowMinL != value))
				{
					this.OnUpWindowMinLChanging(value);
					this.SendPropertyChanging();
					this._UpWindowMinL = value;
					this.SendPropertyChanged("UpWindowMinL");
					this.OnUpWindowMinLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DnWindowMaxH", DbType="Money NOT NULL")]
		public decimal DnWindowMaxH
		{
			get
			{
				return this._DnWindowMaxH;
			}
			set
			{
				if ((this._DnWindowMaxH != value))
				{
					this.OnDnWindowMaxHChanging(value);
					this.SendPropertyChanging();
					this._DnWindowMaxH = value;
					this.SendPropertyChanged("DnWindowMaxH");
					this.OnDnWindowMaxHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastSize", DbType="Decimal(10,3) NOT NULL")]
		public decimal lastSize
		{
			get
			{
				return this._lastSize;
			}
			set
			{
				if ((this._lastSize != value))
				{
					this.OnlastSizeChanging(value);
					this.SendPropertyChanging();
					this._lastSize = value;
					this.SendPropertyChanged("lastSize");
					this.OnlastSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allSize", DbType="Decimal(10,3) NOT NULL")]
		public decimal allSize
		{
			get
			{
				return this._allSize;
			}
			set
			{
				if ((this._allSize != value))
				{
					this.OnallSizeChanging(value);
					this.SendPropertyChanging();
					this._allSize = value;
					this.SendPropertyChanged("allSize");
					this.OnallSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last2CurrentC", DbType="Decimal(10,3) NOT NULL")]
		public decimal last2CurrentC
		{
			get
			{
				return this._last2CurrentC;
			}
			set
			{
				if ((this._last2CurrentC != value))
				{
					this.Onlast2CurrentCChanging(value);
					this.SendPropertyChanging();
					this._last2CurrentC = value;
					this.SendPropertyChanged("last2CurrentC");
					this.Onlast2CurrentCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_all2CurrentC", DbType="Decimal(10,3) NOT NULL")]
		public decimal all2CurrentC
		{
			get
			{
				return this._all2CurrentC;
			}
			set
			{
				if ((this._all2CurrentC != value))
				{
					this.Onall2CurrentCChanging(value);
					this.SendPropertyChanging();
					this._all2CurrentC = value;
					this.SendPropertyChanged("all2CurrentC");
					this.Onall2CurrentCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPairBingoH")]
	public partial class tbPairBingoH
	{
		
		private long _id;
		
		private string _code;
		
		private byte _peakOrValley;
		
		private System.DateTime _date1;
		
		private decimal _price1;
		
		private System.DateTime _date2;
		
		private decimal _price2;
		
		private System.Nullable<int> _cycle;
		
		private System.Nullable<decimal> _slope;
		
		private System.Nullable<int> _cycleDate2ToCurrent;
		
		private System.Nullable<decimal> _derivateCurrentPrice;
		
		private System.Nullable<decimal> _currentPrice;
		
		private System.Nullable<int> _validCrossCount;
		
		private System.Nullable<int> _testCount;
		
		private System.Nullable<decimal> _currentH;
		
		private System.Nullable<decimal> _currentL;
		
		private System.Nullable<int> _crossCount;
		
		private System.Nullable<int> _cycleFrom1stTest;
		
		public tbPairBingoH()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peakOrValley", DbType="TinyInt NOT NULL")]
		public byte peakOrValley
		{
			get
			{
				return this._peakOrValley;
			}
			set
			{
				if ((this._peakOrValley != value))
				{
					this._peakOrValley = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date1", DbType="Date NOT NULL")]
		public System.DateTime date1
		{
			get
			{
				return this._date1;
			}
			set
			{
				if ((this._date1 != value))
				{
					this._date1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price1", DbType="Money NOT NULL")]
		public decimal price1
		{
			get
			{
				return this._price1;
			}
			set
			{
				if ((this._price1 != value))
				{
					this._price1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date2", DbType="Date NOT NULL")]
		public System.DateTime date2
		{
			get
			{
				return this._date2;
			}
			set
			{
				if ((this._date2 != value))
				{
					this._date2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price2", DbType="Money NOT NULL")]
		public decimal price2
		{
			get
			{
				return this._price2;
			}
			set
			{
				if ((this._price2 != value))
				{
					this._price2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycle", DbType="Int")]
		public System.Nullable<int> cycle
		{
			get
			{
				return this._cycle;
			}
			set
			{
				if ((this._cycle != value))
				{
					this._cycle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slope", DbType="Decimal(20,10)")]
		public System.Nullable<decimal> slope
		{
			get
			{
				return this._slope;
			}
			set
			{
				if ((this._slope != value))
				{
					this._slope = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycleDate2ToCurrent", DbType="Int")]
		public System.Nullable<int> cycleDate2ToCurrent
		{
			get
			{
				return this._cycleDate2ToCurrent;
			}
			set
			{
				if ((this._cycleDate2ToCurrent != value))
				{
					this._cycleDate2ToCurrent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_derivateCurrentPrice", DbType="Money")]
		public System.Nullable<decimal> derivateCurrentPrice
		{
			get
			{
				return this._derivateCurrentPrice;
			}
			set
			{
				if ((this._derivateCurrentPrice != value))
				{
					this._derivateCurrentPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currentPrice", DbType="Money")]
		public System.Nullable<decimal> currentPrice
		{
			get
			{
				return this._currentPrice;
			}
			set
			{
				if ((this._currentPrice != value))
				{
					this._currentPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validCrossCount", DbType="Int")]
		public System.Nullable<int> validCrossCount
		{
			get
			{
				return this._validCrossCount;
			}
			set
			{
				if ((this._validCrossCount != value))
				{
					this._validCrossCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testCount", DbType="Int")]
		public System.Nullable<int> testCount
		{
			get
			{
				return this._testCount;
			}
			set
			{
				if ((this._testCount != value))
				{
					this._testCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currentH", DbType="Money")]
		public System.Nullable<decimal> currentH
		{
			get
			{
				return this._currentH;
			}
			set
			{
				if ((this._currentH != value))
				{
					this._currentH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currentL", DbType="Money")]
		public System.Nullable<decimal> currentL
		{
			get
			{
				return this._currentL;
			}
			set
			{
				if ((this._currentL != value))
				{
					this._currentL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crossCount", DbType="Int")]
		public System.Nullable<int> crossCount
		{
			get
			{
				return this._crossCount;
			}
			set
			{
				if ((this._crossCount != value))
				{
					this._crossCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycleFrom1stTest", DbType="Int")]
		public System.Nullable<int> cycleFrom1stTest
		{
			get
			{
				return this._cycleFrom1stTest;
			}
			set
			{
				if ((this._cycleFrom1stTest != value))
				{
					this._cycleFrom1stTest = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
